@echo off
setlocal EnableExtensions DisableDelayedExpansion
set "DIST_DIR=%~dp0"

if exist "%DIST_DIR%LSYL Tunnel Client\make-installer.cmd" (
  call "%DIST_DIR%LSYL Tunnel Client\make-installer.cmd" || exit /b 1
) else (
  echo [ERROR] Client package not found:
  echo   %DIST_DIR%LSYL Tunnel Client
  exit /b 1
)

echo.
echo Client installer is under:
echo   %DIST_DIR%installers
echo Server and Android installers are fixed release outputs and are not regenerated by this client kit command.
endlocal
